.github: simplify prettier script
Signed-off-by: Steve Kuznetsov <stekuznetsov@microsoft.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -46,6 +46,4 @@ jobs:
         run: pnpm ii
         shell: bash
       - name: 🧹 Run prettier
-        run: -|
-          echo "🎨  Checking prettier format..."
-          if ! pnpm prettier --check .; then echo "⚠️  Run 'pnpm prettify' to fix prettier errors & commit the result"; exit 1; fi
+        run: if ! pnpm prettier --check .; then echo "⚠️  Run 'pnpm prettify' to fix prettier errors & commit the result"; exit 1; fi
